server:
  port: 8989

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fisav2?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        hibernate:
        "[format_sql]": true            #SQL 보기 좋게 출력
        "[user_sql_comments]": true     #SQL 생성시 주석 포함
        "[highlight_sql]": true         #SQL 색깔
        "[hbm2ddl.auto]": update
    open-in-view: true
    show-sql: true

  #default 1MB
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  header: "Authorization"
  prefix: "Bearer "
  secret: ${JWT_SECRETKEY2}
  tokenExpirationTime: 18000

project:
  folderPath: "files/"